// src/models/Victim.js
import mongoose from 'mongoose';

const victimSchema = new mongoose.Schema({
    // --- Personal Information (Used for contact and tracking) ---
    name: {
        type: String,
        required: true,
        trim: true,
    },
    contactPhone: { 
        type: String,
        required: true, // Mandatory for contact
    },
    email: {
        type: String,
        // ⬅️ FIX: The 'unique: true' combined with public submission is the source of frequent test errors.
        unique: true, 
        sparse: true // Allows multiple documents with a null email (unregistered users)
    },
    
    // ⬅️ CRITICAL ADDITION: Secure token for public status lookup
    trackingToken: {
        type: String,
        required: true, // Must be generated by controller upon public submission
        unique: true, 
        index: true
    },

    // --- Resource Request Information ---
    resourcesRequested: {
        type: [String], 
        required: true,
    },
    urgencyLevel: {
        type: String,
        enum: ['Low', 'Medium', 'High', 'Critical'],
        default: 'Medium',
    },
    
    // --- GeoJSON location (CRITICAL for matching) ---
    location: {
        type: {
            type: String,
            enum: ['Point'],
            default: 'Point',
            required: true,
        },
        coordinates: { // Stores [longitude, latitude]
            type: [Number],
            required: true,
            validate: {
                validator: function(v) {
                    return v && v.length === 2;
                },
                message: 'Coordinates must contain two numbers: [longitude, latitude]'
            }
        }
    },

    // --- Status of the request and Assignment ---
    requestStatus: {
        type: String,
        enum: ['Pending', 'Assigned', 'InProgress', 'Fulfilled', 'Canceled'],
        default: 'Pending',
    },

    assignedNgoId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'NGO',
    }

}, { timestamps: true });

// CRITICAL: Define the 2dsphere index for Geo-queries
victimSchema.index({ location: '2dsphere' });

const VictimModel = mongoose.model('Victim', victimSchema);
export default VictimModel;